name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run:
        make distcheck
        cd build
        bash ./moto-bootlogo logo.bin
        find . -type f -print | zip archive.zip -@   
    - uses: actions/upload-artifact@v4
      with:
        name: archive.zip
        path: archive.zip
